/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutOrganizer: typeof import('./components/AboutOrganizer.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    CallForAbstractBanner: typeof import('./components/CallForAbstractBanner.vue')['default']
    CallForPaperBanner: typeof import('./components/CallForPaperBanner.vue')['default']
    ContactSponsor: typeof import('./components/ContactSponsor.vue')['default']
    CountdownTimer: typeof import('./components/CountdownTimer.vue')['default']
    CountdownTimerMobile: typeof import('./components/CountdownTimerMobile.vue')['default']
    LoginForm: typeof import('./components/auth/LoginForm.vue')['default']
    RegisterBanner: typeof import('./components/RegisterBanner.vue')['default']
    RegistrationFeesTable: typeof import('./components/RegistrationFeesTable.vue')['default']
    RegistrationForm: typeof import('./components/RegistrationForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SponsorsBanner: typeof import('./components/SponsorsBanner.vue')['default']
    SponsorsPackage: typeof import('./components/SponsorsPackage.vue')['default']
    SubthemeList: typeof import('./components/SubthemeList.vue')['default']
    Transportation: typeof import('./components/Transportation.vue')['default']
    VipList: typeof import('./components/VipList.vue')['default']
  }
}
