/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/About_Us': RouteRecordInfo<'/About_Us', '/About_Us', Record<never, never>, Record<never, never>>,
    '/Abstract_Submission': RouteRecordInfo<'/Abstract_Submission', '/Abstract_Submission', Record<never, never>, Record<never, never>>,
    '/Awards': RouteRecordInfo<'/Awards', '/Awards', Record<never, never>, Record<never, never>>,
    '/Call_For_Paper': RouteRecordInfo<'/Call_For_Paper', '/Call_For_Paper', Record<never, never>, Record<never, never>>,
    '/Committee': RouteRecordInfo<'/Committee', '/Committee', Record<never, never>, Record<never, never>>,
    '/Conference_City': RouteRecordInfo<'/Conference_City', '/Conference_City', Record<never, never>, Record<never, never>>,
    '/Conference_Venue': RouteRecordInfo<'/Conference_Venue', '/Conference_Venue', Record<never, never>, Record<never, never>>,
    '/Contact_Us': RouteRecordInfo<'/Contact_Us', '/Contact_Us', Record<never, never>, Record<never, never>>,
    '/Destination': RouteRecordInfo<'/Destination', '/Destination', Record<never, never>, Record<never, never>>,
    '/Downloads': RouteRecordInfo<'/Downloads', '/Downloads', Record<never, never>, Record<never, never>>,
    '/Exhibition': RouteRecordInfo<'/Exhibition', '/Exhibition', Record<never, never>, Record<never, never>>,
    '/Fullpaper_Submission': RouteRecordInfo<'/Fullpaper_Submission', '/Fullpaper_Submission', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/Important_Dates': RouteRecordInfo<'/Important_Dates', '/Important_Dates', Record<never, never>, Record<never, never>>,
    '/Programs': RouteRecordInfo<'/Programs', '/Programs', Record<never, never>, Record<never, never>>,
    '/Registration_Payment': RouteRecordInfo<'/Registration_Payment', '/Registration_Payment', Record<never, never>, Record<never, never>>,
    '/Topics_Mainpage': RouteRecordInfo<'/Topics_Mainpage', '/Topics_Mainpage', Record<never, never>, Record<never, never>>,
    '/Topics_Subpage': RouteRecordInfo<'/Topics_Subpage', '/Topics_Subpage', Record<never, never>, Record<never, never>>,
    '/Welcome_Message': RouteRecordInfo<'/Welcome_Message', '/Welcome_Message', Record<never, never>, Record<never, never>>,
  }
}
